sylius_resource:
  resources:
    bitbag_sylius_mollie_plugin.mollie_customer:
      driver: doctrine/orm
      classes:
        model: BitBag\SyliusMolliePlugin\Entity\MollieCustomer
        interface: BitBag\SyliusMolliePlugin\Entity\MollieCustomerInterface
